import ErdosProblems.Erdos251.AffineShiftEscape
import ErdosProblems.Erdos251.OrderLatticeDiagonal

/-!
# Erdős #251: the affine `2`-adic cylinder collapses onto its own basepoint

`AffineShiftEscape` lands the forward implication
`affinePowTwo_of_evenIntegral` and reads it as a *hierarchy*: its docstring
asserts that the finite block `B_{h,N,r}` "determines an exponentially sparse
target" and that "`r` may be chosen to suit the arithmetic block".

**That strategic reading is false.**  This module proves the exact converse of
the landed implication.  Substituting the iterate identity
`T_h(N+r) = 2^r·T_h(N) - B_{h,N,r}` into the definition of `RatAffinePowTwo`
cancels the block on both sides:

```
  T_h(N+r) ∈ -B_{h,N,r} + 2^{r+1}ℤ
    ↔ 2^r·T_h(N) - B_{h,N,r} = 2^{r+1}z - B_{h,N,r}
    ↔ T_h(N) = 2z
```

so the cylinder membership is *exactly* even integrality at the basepoint
(`ratAffinePowTwo_iff_evenIntegral`), for **every** depth `r` and independently
of the observed digit block (`ratAffinePowTwo_depth_independent`).  The
apparent `r` extra bits are created by multiplying by `2^r` and destroyed
again by the block translation: relative to the recurrence the cylinder is the
bijective image of `2ℤ` under `x ↦ 2^r x - B_{h,N,r}`, not a sparse subset of
anything.

Two consequences.

*The depth is inert.*  `r = 0` is legal in the landed statement and in the
landed supply hypothesis, and there `B_{h,N,0} = 0`
(`ratAffinePowTwo_zero_iff`).  Adding a hypothesis `0 < r` would not repair
this, because all positive depths are equivalent too.

*The named producer restates its own conclusion.*  Under the even-digit
condition that holds for genuine prime gaps, the cofinal affine escape
hypothesis of `not_eventuallyIntegralTailShift_of_cofinal_affinePowTwo_escape`
is *logically equivalent* to the non-eventual-integrality it was introduced to
derive (`cofinal_affinePowTwo_escape_iff_not_eventuallyIntegral`).  The landed
theorem stays true; it is simply not a consumer awaiting a prime-theoretic
producer.  After one parity-lift step the cylinder is the already-landed
`orderOf` lattice of `OrderLatticeDiagonal`
(`affinePowTwo_succ_iff_orderOf_dvd`), not a refinement of it.

## The repair

The defect is that the cylinder's centre is generated by the same orbit that
is being tested.  A non-adaptive test must compare the finite block against a
**fixed** lattice, with the terminal carry controlled archimedeanly rather than
substituted back in.  `not_eventuallyIntegral_of_cofinal_blockResidue_escape`
does exactly that: if the shifts are bounded by some `bound`, then eventual
integrality forces the block `B_{h,N,r}` to lie within `bound (N+r)` of
`2^r·ℤ`, so cofinally many blocks that are *far from `2^r·ℤ`* rule out eventual
integrality.  The target lattice there does not mention the block, so the
statement is not a pullback of the orbit.  Necessarily `2^(r-1)` must exceed
the terminal bound, so any witness has `r` growing with the basepoint.

## Claim ceiling

**Erdős #251 remains open.**  Nothing here proves irrationality of the prime
dyadic series.  What is settled is that the "affine escape" route did not
reduce that problem, and what replaces it is the bounded-terminal block
residue statement above.
-/

namespace ErdosProblems.Erdos251

/-! ## The collapse -/

/-- **The converse of `affinePowTwo_of_evenIntegral`.**  Membership of the
depth-`r` affine cylinder forces even integrality at the basepoint, with the
*same* witness.  This is the theorem the landed strategic reading excludes. -/
theorem evenIntegral_of_affinePowTwo {g : ℕ → ℤ} {T : ℕ → ℚ}
    (hrec : DyadicTailRecurrence g T) (h N r : ℕ)
    (hAff : RatAffinePowTwo (tailShift T h (N + r))
      (dyadicTailBlock (shiftDigit g h) N r) r) :
    RatEvenIntegral (tailShift T h N) := by
  obtain ⟨z, hz⟩ := hAff
  rw [tail_iterate_eq_pow_mul_sub_block (tailShift_recurrence hrec h) N r] at hz
  refine ⟨z, ?_⟩
  have hne : ((2 : ℚ) ^ r) ≠ 0 := by positivity
  refine mul_left_cancel₀ hne ?_
  push_cast at hz ⊢
  linear_combination hz

/-- **The affine cylinder is exactly even integrality at its basepoint.**
The depth and the observed digit block carry no information whatsoever. -/
theorem ratAffinePowTwo_iff_evenIntegral {g : ℕ → ℤ} {T : ℕ → ℚ}
    (hrec : DyadicTailRecurrence g T) (h N r : ℕ) :
    RatAffinePowTwo (tailShift T h (N + r))
        (dyadicTailBlock (shiftDigit g h) N r) r ↔
      RatEvenIntegral (tailShift T h N) :=
  ⟨evenIntegral_of_affinePowTwo hrec h N r,
    affinePowTwo_of_evenIntegral hrec h N r⟩

/-- **Every alleged depth tests the same basepoint property.**  There is no
`2`-adic hierarchy: depth `r` and depth `s` are interchangeable. -/
theorem ratAffinePowTwo_depth_independent {g : ℕ → ℤ} {T : ℕ → ℚ}
    (hrec : DyadicTailRecurrence g T) (h N r s : ℕ) :
    RatAffinePowTwo (tailShift T h (N + r))
        (dyadicTailBlock (shiftDigit g h) N r) r ↔
      RatAffinePowTwo (tailShift T h (N + s))
        (dyadicTailBlock (shiftDigit g h) N s) s := by
  rw [ratAffinePowTwo_iff_evenIntegral hrec h N r,
    ratAffinePowTwo_iff_evenIntegral hrec h N s]

/-- **The block-free corner.**  Depth `0` is legal in the landed statement and
carries an empty block, so the supply hypothesis can be witnessed with no
arithmetic input at all. -/
theorem ratAffinePowTwo_zero_iff {g : ℕ → ℤ} {T : ℕ → ℚ}
    (hrec : DyadicTailRecurrence g T) (h N : ℕ) :
    RatAffinePowTwo (tailShift T h N)
        (dyadicTailBlock (shiftDigit g h) N 0) 0 ↔
      RatEvenIntegral (tailShift T h N) := by
  have := ratAffinePowTwo_iff_evenIntegral hrec h N 0
  simpa using this

/-! ## Collapse onto the landed order lattice -/

/-- The converse of `evenIntegral_succ`: with an even difference digit, even
integrality one step later is *equivalent* to ordinary integrality before. -/
theorem evenIntegral_succ_iff_integral {g : ℕ → ℤ} {T : ℕ → ℚ}
    (hrec : DyadicTailRecurrence g T) (h N : ℕ)
    (heven : ∃ k : ℤ, g (N + h + 1) - g (N + 1) = 2 * k) :
    RatEvenIntegral (tailShift T h (N + 1)) ↔ RatIntegral (tailShift T h N) := by
  refine ⟨?_, fun hInt => evenIntegral_succ hrec h N hInt heven⟩
  rintro ⟨z, hz⟩
  obtain ⟨k, hk⟩ := heven
  refine ⟨z + k, ?_⟩
  have hstep := tailShift_succ hrec h N
  have hd : ((g (N + h + 1) : ℤ) : ℚ) - ((g (N + 1) : ℤ) : ℚ) = ((2 * k : ℤ) : ℚ) := by
    have hcast : ((g (N + h + 1) - g (N + 1) : ℤ) : ℚ) = ((2 * k : ℤ) : ℚ) := by rw [hk]
    push_cast at hcast ⊢
    linarith
  rw [hz] at hstep
  push_cast at hstep hd ⊢
  linarith

/-- **The cylinder is the landed `orderOf` lattice.**  After the obligatory
parity-lift step the affine class is exactly `OrderLatticeDiagonal`'s
classifier — independently of the depth `r` and of the observed block.  It is
therefore not a refinement of that lattice. -/
theorem affinePowTwo_succ_iff_orderOf_dvd {g : ℕ → ℤ} {T : ℕ → ℚ}
    (hrec : DyadicTailRecurrence g T) (h N r : ℕ)
    (heven : ∃ k : ℤ, g (N + h + 1) - g (N + 1) = 2 * k) :
    RatAffinePowTwo (tailShift T h (N + 1 + r))
        (dyadicTailBlock (shiftDigit g h) (N + 1) r) r ↔
      orderOf (2 : ZMod (T N).den) ∣ h := by
  rw [ratAffinePowTwo_iff_evenIntegral hrec h (N + 1) r,
    evenIntegral_succ_iff_integral hrec h N heven,
    tailShift_integral_iff_orderOf_dvd hrec N h]

/-! ## The named producer is equivalent to its own conclusion -/

/-- **Circularity.**  The cofinal affine-escape hypothesis of
`not_eventuallyIntegralTailShift_of_cofinal_affinePowTwo_escape` is logically
equivalent to the non-eventual-integrality it was introduced to derive.  The
reverse implication needs no arithmetic: depth `0` witnesses it. -/
theorem cofinal_affinePowTwo_escape_iff_not_eventuallyIntegral
    {g : ℕ → ℤ} {T : ℕ → ℚ} (hrec : DyadicTailRecurrence g T) (h : ℕ)
    (hdiffEven : ∀ N, ∃ k : ℤ, g (N + h + 1) - g (N + 1) = 2 * k) :
    (∀ N₀ : ℕ, ∃ N r : ℕ, N₀ < N ∧
        ¬ RatAffinePowTwo (tailShift T h (N + r))
          (dyadicTailBlock (shiftDigit g h) N r) r) ↔
      ¬ ∃ N₀, ∀ N, N₀ ≤ N → RatIntegral (tailShift T h N) := by
  refine ⟨not_eventuallyIntegralTailShift_of_cofinal_affinePowTwo_escape
    hrec h hdiffEven, ?_⟩
  intro hnot N₀
  have hnon : ∃ N, N₀ < N ∧ ¬ RatIntegral (tailShift T h N) := by
    by_contra hnone
    push_neg at hnone
    exact hnot ⟨N₀ + 1, fun N hN => hnone N (by omega)⟩
  obtain ⟨N, hN, hNonInt⟩ := hnon
  refine ⟨N, 0, hN, ?_⟩
  intro hAff
  obtain ⟨z, hz⟩ := (ratAffinePowTwo_iff_evenIntegral hrec h N 0).1 hAff
  exact hNonInt ⟨2 * z, by exact_mod_cast hz⟩

/-! ## The non-adaptive replacement

The collapse above is caused by testing the orbit against a target built from
the orbit's own digits.  The following producer compares the finite block with
the **fixed** lattice `2^r·ℤ`, and controls the unknown terminal carry by an
archimedean bound rather than by substitution. -/

/-- **Eventual integrality pins the finite block to `2^r·ℤ`.**  If the shift is
integral at `N`, then the block `B_{h,N,r}` differs from a point of `2^r·ℤ` by
exactly the terminal shift `T_h(N+r)`.  Nothing here is a pullback: the lattice
`2^r·ℤ` does not mention the block. -/
theorem blockResidue_eq_terminal_of_integral {g : ℕ → ℤ} {T : ℕ → ℚ}
    (hrec : DyadicTailRecurrence g T) (h N r : ℕ)
    (hInt : RatIntegral (tailShift T h N)) :
    ∃ z : ℤ, ((dyadicTailBlock (shiftDigit g h) N r : ℤ) : ℚ) - 2 ^ r * (z : ℚ)
      = -tailShift T h (N + r) := by
  obtain ⟨z, hz⟩ := hInt
  refine ⟨z, ?_⟩
  rw [tail_iterate_eq_pow_mul_sub_block (tailShift_recurrence hrec h) N r, hz]
  ring

/-- **The corrected producer.**  Given any archimedean bound on the shifts,
cofinally many finite blocks lying further than that bound from `2^r·ℤ` rule
out eventual integrality.  Unlike the affine cylinder, the target here is a
fixed lattice, so the hypothesis is not a restatement of the conclusion. -/
theorem not_eventuallyIntegral_of_cofinal_blockResidue_escape
    {g : ℕ → ℤ} {T : ℕ → ℚ} (hrec : DyadicTailRecurrence g T) (h : ℕ)
    (bound : ℕ → ℚ)
    (hbound : ∀ N, |tailShift T h N| ≤ bound N)
    (hsupply : ∀ N₀ : ℕ, ∃ N r : ℕ, N₀ < N ∧
      ∀ z : ℤ, bound (N + r) <
        |((dyadicTailBlock (shiftDigit g h) N r : ℤ) : ℚ) - 2 ^ r * (z : ℚ)|) :
    ¬ ∃ N₀, ∀ N, N₀ ≤ N → RatIntegral (tailShift T h N) := by
  rintro ⟨N₀, hInt⟩
  obtain ⟨N, r, hN, hfar⟩ := hsupply N₀
  obtain ⟨z, hz⟩ := blockResidue_eq_terminal_of_integral hrec h N r
    (hInt N (by omega))
  have hlt := hfar z
  rw [hz, abs_neg] at hlt
  exact absurd (hbound (N + r)) (not_le.mpr hlt)

/-! ## The fixed-lattice repair also collapses under subexponential bounds -/

/-- A bound is dyadically dominated when every fixed rational denominator is
eventually overwhelmed by the depth scale.  Polynomial bounds have this
property; the definition isolates exactly the growth input used below. -/
def DyadicScaleDominates (bound : ℕ → ℚ) : Prop :=
  ∀ N q : ℕ, 0 < q → ∃ r : ℕ,
    2 * bound (N + r) * q < 2 ^ r

/-- A nonzero rational is separated from every integer by the reciprocal of
its reduced denominator. -/
theorem one_div_den_le_abs_sub_int_of_ne
    (x : ℚ) (z : ℤ) (hne : x ≠ z) :
    (1 : ℚ) / x.den ≤ |x - z| := by
  let y : ℚ := x - z
  have hy : y ≠ 0 := sub_ne_zero.mpr hne
  have hden : y.den = x.den := by
    simpa [y] using Rat.sub_intCast_den x z
  have hnumZ : (1 : ℤ) ≤ |y.num| :=
    Int.one_le_abs ((Rat.num_ne_zero).2 hy)
  have hnumQ : (1 : ℚ) ≤ |(y.num : ℚ)| := by
    exact_mod_cast hnumZ
  rw [← hden]
  calc
    (1 : ℚ) / y.den ≤ |(y.num : ℚ)| / y.den :=
      div_le_div_of_nonneg_right hnumQ (by positivity)
    _ = |y| := by
      rw [← abs_of_pos (show (0 : ℚ) < y.den by positivity), ← abs_div,
        Rat.num_div_den]
    _ = |x - z| := rfl

/-- **The alleged fixed-lattice escape is forced by basepoint
nonintegrality.**  Under a dyadically dominated terminal bound, every
nonintegral rational basepoint automatically has some depth whose observed
block lies farther than the terminal bound from `2^r * ℤ`.  No property of
the digit word is used beyond the recurrence identity. -/
theorem exists_blockResidue_escape_of_not_integral
    {g : ℕ → ℤ} {T : ℕ → ℚ} (hrec : DyadicTailRecurrence g T) (h : ℕ)
    (bound : ℕ → ℚ)
    (hbound : ∀ n, |tailShift T h n| ≤ bound n)
    (hscale : DyadicScaleDominates bound) (N : ℕ)
    (hNon : ¬ RatIntegral (tailShift T h N)) :
    ∃ r : ℕ, ∀ z : ℤ, bound (N + r) <
      |((dyadicTailBlock (shiftDigit g h) N r : ℤ) : ℚ) - 2 ^ r * (z : ℚ)| := by
  obtain ⟨r, hr⟩ := hscale N (tailShift T h N).den (tailShift T h N).den_pos
  refine ⟨r, fun z => ?_⟩
  have hne : tailShift T h N ≠ (z : ℚ) := by
    intro hz
    exact hNon ⟨z, hz⟩
  have hdist := one_div_den_le_abs_sub_int_of_ne (tailShift T h N) z hne
  have hdenPos : (0 : ℚ) < (tailShift T h N).den := by positivity
  have hscale' :
      2 * bound (N + r) <
        (2 : ℚ) ^ r / (tailShift T h N).den := by
    rw [lt_div_iff₀ hdenPos]
    exact_mod_cast hr
  have hpowNonneg : (0 : ℚ) ≤ (2 : ℚ) ^ r := by positivity
  have hscaled :
      (2 : ℚ) ^ r / (tailShift T h N).den ≤
        |(2 : ℚ) ^ r * (tailShift T h N - z)| := by
    rw [abs_mul, abs_of_nonneg hpowNonneg]
    exact mul_le_mul_of_nonneg_left (by simpa [div_eq_mul_inv] using hdist) hpowNonneg
  have hiter := tail_iterate_eq_pow_mul_sub_block
    (tailShift_recurrence hrec h) N r
  have hboundTerminal : |tailShift T h (N + r)| ≤ bound (N + r) := by
    exact hbound (N + r)
  have htriangle :
      |(2 : ℚ) ^ r * (tailShift T h N - z)| ≤
        |((dyadicTailBlock (shiftDigit g h) N r : ℤ) : ℚ) -
            2 ^ r * (z : ℚ)| + |tailShift T h (N + r)| := by
    have hid :
        (2 : ℚ) ^ r * (tailShift T h N - z) =
          (((dyadicTailBlock (shiftDigit g h) N r : ℤ) : ℚ) -
              2 ^ r * (z : ℚ)) + tailShift T h (N + r) := by
      push_cast at hiter ⊢
      linarith
    rw [hid]
    exact abs_add_le _ _
  nlinarith

/-- **Second circularity theorem.**  For every dyadically
dominated bound, cofinal escape of the non-adaptive block from `2^r * ℤ` is
equivalent to the non-eventual-integrality conclusion it was meant to prove.
Thus polynomial terminal bounds cannot turn this fixed-lattice formulation
into an independent prime-theoretic producer. -/
theorem cofinal_blockResidue_escape_iff_not_eventuallyIntegral
    {g : ℕ → ℤ} {T : ℕ → ℚ} (hrec : DyadicTailRecurrence g T) (h : ℕ)
    (bound : ℕ → ℚ)
    (hbound : ∀ N, |tailShift T h N| ≤ bound N)
    (hscale : DyadicScaleDominates bound) :
    (∀ N₀ : ℕ, ∃ N r : ℕ, N₀ < N ∧
      ∀ z : ℤ, bound (N + r) <
        |((dyadicTailBlock (shiftDigit g h) N r : ℤ) : ℚ) - 2 ^ r * (z : ℚ)|) ↔
      ¬ ∃ N₀, ∀ N, N₀ ≤ N → RatIntegral (tailShift T h N) := by
  constructor
  · exact not_eventuallyIntegral_of_cofinal_blockResidue_escape
      hrec h bound hbound
  · intro hnot N₀
    have hnon : ∃ N, N₀ < N ∧ ¬ RatIntegral (tailShift T h N) := by
      by_contra hnone
      push_neg at hnone
      exact hnot ⟨N₀ + 1, fun N hN => hnone N (by omega)⟩
    obtain ⟨N, hN, hNon⟩ := hnon
    obtain ⟨r, hr⟩ := exists_blockResidue_escape_of_not_integral
      hrec h bound hbound hscale N hNon
    exact ⟨N, r, hN, hr⟩

end ErdosProblems.Erdos251
