import Mathlib.Data.ZMod.Basic
import Mathlib.RingTheory.Coprime.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Module.BigOperators
import Mathlib.Algebra.Module.Prod
import Mathlib.Data.Fintype.Pi
import Lean.Elab.Tactic.Omega
import Mathlib.Tactic.Choose
import Mathlib.Tactic.Push
import Mathlib.Tactic.Ring

/-!
# Erdős #1049: the Bézout–Plücker normal form for endpoint jets

`ZudilinConeArithmetic.fourJetSignature_card` counts the *whole ambient*
endpoint-jet target, `(3^R)^2 · (2^S)^2`, and its binary-selector pigeonhole
therefore needs rank `4R + 2S`.  That count is wasteful whenever the rows
share arithmetic: the four jets are two coordinates modulo `N = 2^S·3^R` by
CRT, and one determinant-one shear makes one of those coordinates *free*
while the other consists exactly of exterior minors.

## The normal form

Fix an anchor `(a,b)` that is unimodular modulo `N`, i.e. `u·a + v·b = 1` for
some `u, v`.  The shear

`T = ![![u, v], ![-b, a]]`,   `det T = u·a + v·b = 1`

sends the anchor to `(1,0)` and a general row `(A,B)` to `(u·A + v·B, a·B - b·A)`.
Its second coordinate **is** the exterior minor against the anchor.  Hence the
subgroup generated by the rows is `R × ⟨minors⟩`, so
`|H_N| = N²/d` with `d = gcd(N, minors)`, and the cokernel is cyclic of
order `d` — every `2`-adic anchor-minor depth saves one selector and every
`3`-adic depth saves two, with no logarithmic estimate.

At maximal collapse (`d = N`, every anchor minor vanishing) the target has
only `N` elements instead of `N²`, so the ambient rank threshold `4R + 2S`
drops to `2R + S`.  `binary_row_collision_of_anchor_det_zero` is that halving,
proved from `card R < 2 ^ card ι` rather than from `card (R × R)`.

## Claim ceiling

**Erdős #1049 remains open.**  This is the linear-algebraic half only.  It
supplies a smaller jet target; it does not supply the analytic remainder
non-vanishing, and `ZudilinConeArithmetic` continues to record that the
collision theorem yields a kernel element, not a contradiction.
-/

namespace ErdosProblems.Erdos1049.BezoutPluckerJets

section BezoutPlucker

variable {R : Type*} [CommRing R]

/-- The determinant-one Bézout shear based at the unimodular anchor `(a,b)`.
Its second coordinate is the exterior minor `a·y - b·x` against the anchor. -/
def bezoutPluckerEquiv (a b u v : R) (h : u * a + v * b = 1) : R × R ≃+ R × R where
  toFun z := (u * z.1 + v * z.2, a * z.2 - b * z.1)
  invFun z := (a * z.1 - v * z.2, b * z.1 + u * z.2)
  left_inv := by
    rintro ⟨x, y⟩
    apply Prod.ext <;> dsimp
    · calc a * (u * x + v * y) - v * (a * y - b * x) = (u * a + v * b) * x := by ring
        _ = x := by rw [h, one_mul]
    · calc b * (u * x + v * y) + u * (a * y - b * x) = (u * a + v * b) * y := by ring
        _ = y := by rw [h, one_mul]
  right_inv := by
    rintro ⟨x, y⟩
    apply Prod.ext <;> dsimp
    · calc u * (a * x - v * y) + v * (b * x + u * y) = (u * a + v * b) * x := by ring
        _ = x := by rw [h, one_mul]
    · calc a * (b * x + u * y) - b * (a * x - v * y) = (u * a + v * b) * y := by ring
        _ = y := by rw [h, one_mul]
  map_add' := by
    rintro ⟨x₁, y₁⟩ ⟨x₂, y₂⟩
    apply Prod.ext <;> dsimp <;> ring

@[simp] theorem bezoutPluckerEquiv_apply (a b u v : R) (h : u * a + v * b = 1) (x y : R) :
    bezoutPluckerEquiv a b u v h (x, y) = (u * x + v * y, a * y - b * x) := rfl

@[simp] theorem bezoutPluckerEquiv_anchor (a b u v : R) (h : u * a + v * b = 1) :
    bezoutPluckerEquiv a b u v h (a, b) = (1, 0) := by
  change (u * a + v * b, a * b - b * a) = (1, 0)
  rw [h]
  simp [mul_comm]

/-- A vector with vanishing exterior minor against a unimodular anchor is a
scalar multiple of that anchor. -/
theorem exists_scalar_eq_of_det_eq_zero {a b x y : R}
    (hab : IsCoprime a b) (hdet : a * y - b * x = 0) :
    ∃ c : R, x = c * a ∧ y = c * b := by
  rcases hab with ⟨u, v, huv⟩
  have hxy : a * y = b * x := sub_eq_zero.mp hdet
  refine ⟨u * x + v * y, ?_, ?_⟩
  · calc x = (u * a + v * b) * x := by rw [huv, one_mul]
      _ = u * a * x + v * (b * x) := by ring
      _ = u * a * x + v * (a * y) := by rw [← hxy]
      _ = (u * x + v * y) * a := by ring
  · calc y = (u * a + v * b) * y := by rw [huv, one_mul]
      _ = u * (a * y) + v * b * y := by ring
      _ = u * (b * x) + v * b * y := by rw [hxy]
      _ = (u * x + v * y) * b := by ring

/-- **Minor propagation.**  Vanishing of every minor against one unimodular
anchor forces *every* pairwise minor to vanish: the anchor's `|I| - 1` minors
determine the entire determinantal divisor. -/
theorem anchor_det_zero_forces_all_det_zero {ι : Type*} (w : ι → R × R) {a b : R}
    (hab : IsCoprime a b) (hdet : ∀ i, a * (w i).2 - b * (w i).1 = 0) :
    ∀ i j, (w i).1 * (w j).2 - (w i).2 * (w j).1 = 0 := by
  intro i j
  obtain ⟨cᵢ, hi₁, hi₂⟩ := exists_scalar_eq_of_det_eq_zero hab (hdet i)
  obtain ⟨cⱼ, hj₁, hj₂⟩ := exists_scalar_eq_of_det_eq_zero hab (hdet j)
  rw [hi₁, hi₂, hj₁, hj₂]
  ring

end BezoutPlucker

section BinaryPigeonhole

/-- Binary-selector pigeonhole, with the cardinality written in the form the
endpoint-jet application needs. -/
theorem exists_binary_collision_of_card_lt {ι α : Type*} [Fintype ι] [Fintype α]
    (f : (ι → Bool) → α) (hcard : Fintype.card α < 2 ^ Fintype.card ι) :
    ∃ s t : ι → Bool, s ≠ t ∧ f s = f t := by
  classical
  by_contra hbad
  push Not at hbad
  have hinj : Function.Injective f := fun s t hst => by
    by_contra hne
    exact hne (by simpa using (hbad s t hne hst).elim)
  have hle : Fintype.card (ι → Bool) ≤ Fintype.card α := Fintype.card_le_of_injective f hinj
  simp only [Fintype.card_fun, Fintype.card_bool] at hle
  omega

end BinaryPigeonhole

section MaximalCollapse

variable {R ι : Type*} [CommRing R] [Fintype R] [Fintype ι]

/-- **The halved threshold.**  If every row is collinear with one unimodular
anchor, binary selector sums take at most `card R` values, not `(card R)²`.
For the endpoint jets at `N = 2^S·3^R` this replaces the ambient requirement
`4R + 2S` by `2R + S`. -/
theorem binary_row_collision_of_anchor_det_zero (w : ι → R × R) {a b : R}
    (hab : IsCoprime a b) (hdet : ∀ i, a * (w i).2 - b * (w i).1 = 0)
    (hcard : Fintype.card R < 2 ^ Fintype.card ι) :
    ∃ s t : ι → Bool, s ≠ t ∧
      (∑ i, if s i then w i else 0) = ∑ i, if t i then w i else 0 := by
  classical
  choose c hc₁ hc₂ using fun i => exists_scalar_eq_of_det_eq_zero hab (hdet i)
  have hw : ∀ i, w i = c i • (a, b) := by
    intro i
    apply Prod.ext
    · simpa [smul_eq_mul] using hc₁ i
    · simpa [smul_eq_mul] using hc₂ i
  set f : (ι → Bool) → R := fun s => ∑ i, if s i then c i else 0 with hf
  have hsum : ∀ s : ι → Bool, (∑ i, if s i then w i else 0) = f s • (a, b) := by
    intro s
    rw [hf]
    simp only [Finset.sum_smul]
    refine Finset.sum_congr rfl fun i _ => ?_
    by_cases hs : s i <;> simp [hs, hw i]
  obtain ⟨s, t, hne, hst⟩ := exists_binary_collision_of_card_lt f hcard
  exact ⟨s, t, hne, by rw [hsum s, hsum t, hst]⟩

end MaximalCollapse

/-! ## The `ZMod N` instance -/

/-- Every row of a family whose entries are units at each prime of `N` is an
admissible anchor; this is the lattice form of the endpoint unit hypothesis. -/
theorem isCoprime_of_isUnit_left {R : Type*} [CommRing R] {a b : R} (ha : IsUnit a) :
    IsCoprime a b := by
  obtain ⟨u, hu⟩ := ha
  exact ⟨(u⁻¹ : Rˣ), 0, by simp [← hu, ← Units.val_mul]⟩

/-- A unit second coordinate is equally an admissible Bézout--Plücker anchor. -/
theorem isCoprime_of_isUnit_right {R : Type*} [CommRing R] {a b : R} (hb : IsUnit b) :
    IsCoprime a b := (isCoprime_of_isUnit_left (a := b) (b := a) hb).symm

/-- **Unimodular adjacent-to-tail propagation.**  If every row is unimodular,
vanishing of every adjacent minor forces vanishing of every
pairwise minor.  Thus a local divisor shared by all adjacent minors really does
compress the full tail after reduction modulo that divisor; checking only one
attractive adjacent determinant is not enough.

The proof is algebraic, not asymptotic: each next row is a scalar multiple of
the preceding row, so induction places the whole sequence on the first row's
line. -/
theorem adjacent_det_zero_forces_all_det_zero_of_isCoprime {R : Type*} [CommRing R]
    (w : ℕ → R × R) (hcoprime : ∀ n, IsCoprime (w n).1 (w n).2)
    (hadj : ∀ n, (w n).1 * (w (n + 1)).2 - (w n).2 * (w (n + 1)).1 = 0) :
    ∀ i j, (w i).1 * (w j).2 - (w i).2 * (w j).1 = 0 := by
  have hspan : ∀ n, ∃ c : R, (w n).1 = c * (w 0).1 ∧ (w n).2 = c * (w 0).2 := by
    intro n
    induction n with
    | zero => exact ⟨1, by simp, by simp⟩
    | succ n ih =>
        obtain ⟨c, hc₁, hc₂⟩ := ih
        obtain ⟨d, hd₁, hd₂⟩ := exists_scalar_eq_of_det_eq_zero
          (hcoprime n) (by simpa [Nat.add_comm] using hadj n)
        refine ⟨d * c, ?_, ?_⟩
        · rw [hd₁, hc₁]
          ring
        · rw [hd₂, hc₂]
          ring
  intro i j
  obtain ⟨c, hi₁, hi₂⟩ := hspan i
  obtain ⟨d, hj₁, hj₂⟩ := hspan j
  rw [hi₁, hi₂, hj₁, hj₂]
  ring


/-- **Adjacent-to-tail propagation.**  For a sequence whose second coordinate
is always a unit, vanishing of every adjacent minor forces vanishing of every
pairwise minor.  Thus a local divisor shared by all adjacent minors really does
compress the full tail after reduction modulo that divisor; checking only one
attractive adjacent determinant is not enough.

The proof is algebraic, not asymptotic: each next row is a scalar multiple of
the preceding row, so induction places the whole sequence on the first row's
line. -/
theorem adjacent_det_zero_forces_all_det_zero {R : Type*} [CommRing R]
    (w : ℕ → R × R) (hunit : ∀ n, IsUnit (w n).2)
    (hadj : ∀ n, (w n).1 * (w (n + 1)).2 - (w n).2 * (w (n + 1)).1 = 0) :
    ∀ i j, (w i).1 * (w j).2 - (w i).2 * (w j).1 = 0 := by
  have hspan : ∀ n, ∃ c : R, (w n).1 = c * (w 0).1 ∧ (w n).2 = c * (w 0).2 := by
    intro n
    induction n with
    | zero => exact ⟨1, by simp, by simp⟩
    | succ n ih =>
        obtain ⟨c, hc₁, hc₂⟩ := ih
        obtain ⟨d, hd₁, hd₂⟩ := exists_scalar_eq_of_det_eq_zero
          (isCoprime_of_isUnit_right (hunit n)) (by simpa [Nat.add_comm] using hadj n)
        refine ⟨d * c, ?_, ?_⟩
        · rw [hd₁, hc₁]
          ring
        · rw [hd₂, hc₂]
          ring
  intro i j
  obtain ⟨c, hi₁, hi₂⟩ := hspan i
  obtain ⟨d, hj₁, hj₂⟩ := hspan j
  rw [hi₁, hi₂, hj₁, hj₂]
  ring

/-- The exact modular consumer for moving-tail Plücker experiments.  Once the
primitive q-Apéry denominator coordinates are units modulo `N` and every
adjacent tail minor vanishes modulo `N`, all tail minors vanish modulo `N`.
Supplying those all-index q-Apéry hypotheses remains a separate obligation. -/
theorem zmod_tail_pair_det_zero_of_adjacent_det_zero {N : ℕ} [NeZero N]
    (w : ℕ → ZMod N × ZMod N) (hunit : ∀ n, IsUnit (w n).2)
    (hadj : ∀ n, (w n).1 * (w (n + 1)).2 - (w n).2 * (w (n + 1)).1 = 0) :
    ∀ i j, (w i).1 * (w j).2 - (w i).2 * (w j).1 = 0 :=
  adjacent_det_zero_forces_all_det_zero w hunit hadj

/-- **Moving-tail selector collision.**  An arbitrarily long modular tail with
unit second coordinates and zero adjacent minors admits a nontrivial binary
selector collision as soon as the tail width exceeds the modulus cardinality
threshold.  This composes adjacent-to-tail propagation with the exact
Bézout--Plücker image collapse; it still says nothing about escape from an
analytic-remainder nullspace. -/
theorem zmod_binary_tail_collision_of_adjacent_det_zero {N k : ℕ} [NeZero N]
    (w : ℕ → ZMod N × ZMod N) (hunit : ∀ n, IsUnit (w n).2)
    (hadj : ∀ n, (w n).1 * (w (n + 1)).2 - (w n).2 * (w (n + 1)).1 = 0)
    (hcard : N < 2 ^ k) :
    ∃ s t : Fin k → Bool, s ≠ t ∧
      (∑ i, if s i then w i else 0) = ∑ i, if t i then w i else 0 := by
  let u : Fin k → ZMod N × ZMod N := fun i => w i
  have hall := zmod_tail_pair_det_zero_of_adjacent_det_zero w hunit hadj
  have hanchor : ∀ i, (w 0).1 * (u i).2 - (w 0).2 * (u i).1 = 0 := by
    intro i
    exact hall 0 i
  have hcard' : Fintype.card (ZMod N) < 2 ^ Fintype.card (Fin k) := by
    simpa using hcard
  exact binary_row_collision_of_anchor_det_zero u
    (isCoprime_of_isUnit_right (hunit 0)) hanchor hcard'

/-- The explicit `2`/`3` local-depth threshold.  A tail collapsed modulo
`2^S 3^R` needs only `S+2R` binary rows, rather than the ambient two-channel
threshold `2S+4R`, because `3^R<2^(2R)` for positive `R`. -/
theorem zmod_binary_tail_collision_of_two_three_depth {R S k : ℕ}
    [NeZero (2 ^ S * 3 ^ R)]
    (w : ℕ → ZMod (2 ^ S * 3 ^ R) × ZMod (2 ^ S * 3 ^ R))
    (hunit : ∀ n, IsUnit (w n).2)
    (hadj : ∀ n, (w n).1 * (w (n + 1)).2 - (w n).2 * (w (n + 1)).1 = 0)
    (hR : 0 < R) (hrank : S + 2 * R ≤ k) :
    ∃ s t : Fin k → Bool, s ≠ t ∧
      (∑ i, if s i then w i else 0) = ∑ i, if t i then w i else 0 := by
  apply zmod_binary_tail_collision_of_adjacent_det_zero w hunit hadj
  have hthree : 3 ^ R < 4 ^ R := Nat.pow_lt_pow_left (by omega) hR.ne'
  have htwo : 0 < (2 : ℕ) ^ S := Nat.pow_pos (by norm_num)
  calc
    2 ^ S * 3 ^ R < 2 ^ S * 4 ^ R := (Nat.mul_lt_mul_left htwo).mpr hthree
    _ = 2 ^ (S + 2 * R) := by
      rw [show (4 : ℕ) = 2 ^ 2 by norm_num, ← pow_mul, ← pow_add]
    _ ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) hrank

/-- **Moving-tail selector collision.**  An arbitrarily long modular tail with
unimodular rows and zero adjacent minors admits a nontrivial binary
selector collision as soon as the tail width exceeds the modulus cardinality
threshold.  This composes adjacent-to-tail propagation with the exact
Bézout--Plücker image collapse; it still says nothing about escape from an
analytic-remainder nullspace. -/
theorem zmod_binary_tail_collision_of_adjacent_det_zero_of_isCoprime {N k : ℕ} [NeZero N]
    (w : ℕ → ZMod N × ZMod N) (hcoprime : ∀ n, IsCoprime (w n).1 (w n).2)
    (hadj : ∀ n, (w n).1 * (w (n + 1)).2 - (w n).2 * (w (n + 1)).1 = 0)
    (hcard : N < 2 ^ k) :
    ∃ s t : Fin k → Bool, s ≠ t ∧
      (∑ i, if s i then w i else 0) = ∑ i, if t i then w i else 0 := by
  let u : Fin k → ZMod N × ZMod N := fun i => w i
  have hall := adjacent_det_zero_forces_all_det_zero_of_isCoprime w hcoprime hadj
  have hanchor : ∀ i, (w 0).1 * (u i).2 - (w 0).2 * (u i).1 = 0 := by
    intro i
    exact hall 0 i
  have hcard' : Fintype.card (ZMod N) < 2 ^ Fintype.card (Fin k) := by
    simpa using hcard
  exact binary_row_collision_of_anchor_det_zero u
    (hcoprime 0) hanchor hcard'

/-- The explicit `2`/`3` local-depth threshold.  A tail collapsed modulo
`2^S 3^R` needs only `S+2R` binary rows, rather than the ambient two-channel
threshold `2S+4R`, because `3^R<2^(2R)` for positive `R`. -/
theorem zmod_binary_tail_collision_of_two_three_depth_of_isCoprime {R S k : ℕ}
    [NeZero (2 ^ S * 3 ^ R)]
    (w : ℕ → ZMod (2 ^ S * 3 ^ R) × ZMod (2 ^ S * 3 ^ R))
    (hcoprime : ∀ n, IsCoprime (w n).1 (w n).2)
    (hadj : ∀ n, (w n).1 * (w (n + 1)).2 - (w n).2 * (w (n + 1)).1 = 0)
    (hR : 0 < R) (hrank : S + 2 * R ≤ k) :
    ∃ s t : Fin k → Bool, s ≠ t ∧
      (∑ i, if s i then w i else 0) = ∑ i, if t i then w i else 0 := by
  apply zmod_binary_tail_collision_of_adjacent_det_zero_of_isCoprime w hcoprime hadj
  have hthree : 3 ^ R < 4 ^ R := Nat.pow_lt_pow_left (by omega) hR.ne'
  have htwo : 0 < (2 : ℕ) ^ S := Nat.pow_pos (by norm_num)
  calc
    2 ^ S * 3 ^ R < 2 ^ S * 4 ^ R := (Nat.mul_lt_mul_left htwo).mpr hthree
    _ = 2 ^ (S + 2 * R) := by
      rw [show (4 : ℕ) = 2 ^ 2 by norm_num, ← pow_mul, ← pow_add]
    _ ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) hrank


/-- **Endpoint-jet collapse at a modulus.**  With a unit anchor coordinate and
every anchor minor vanishing, `card (ZMod N)` selectors — not `card (ZMod N)²`
— already force a signed relation. -/
theorem zmod_binary_row_collision_of_anchor_det_zero {N : ℕ} [NeZero N] {ι : Type*}
    [Fintype ι] [DecidableEq ι] (w : ι → ZMod N × ZMod N) {a b : ZMod N}
    (ha : IsUnit a) (hdet : ∀ i, a * (w i).2 - b * (w i).1 = 0)
    (hcard : N < 2 ^ Fintype.card ι) :
    ∃ s t : ι → Bool, s ≠ t ∧
      (∑ i, if s i then w i else 0) = ∑ i, if t i then w i else 0 := by
  have hcard' : Fintype.card (ZMod N) < 2 ^ Fintype.card ι := by
    rwa [ZMod.card N]
  exact binary_row_collision_of_anchor_det_zero w (isCoprime_of_isUnit_left ha) hdet hcard'

end ErdosProblems.Erdos1049.BezoutPluckerJets
